# Generated by Django 4.0.5 on 2022-07-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('fnm', models.CharField(max_length=127)),
                ('lnm', models.CharField(max_length=127)),
                ('unm', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('pno', models.CharField(max_length=127)),
                ('password', models.CharField(max_length=127)),
                ('role', models.CharField(max_length=127)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
