# Generated by Django 4.0.5 on 2022-07-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_user_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('breed', models.CharField(max_length=127)),
                ('color', models.CharField(max_length=127)),
                ('age', models.CharField(max_length=127)),
                ('size', models.CharField(max_length=127)),
                ('weight', models.CharField(max_length=127)),
                ('gender', models.CharField(max_length=127)),
                ('image', models.CharField(max_length=127)),
                ('addedby', models.CharField(max_length=127)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
