# Generated by Django 4.0.5 on 2022-07-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('fnm', models.CharField(max_length=127)),
                ('lnm', models.CharField(max_length=127)),
                ('unm', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('pno', models.CharField(max_length=127)),
                ('address', models.CharField(max_length=127)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
