# Generated by Django 4.0.5 on 2022-07-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=127)),
                ('pno', models.CharField(max_length=127)),
                ('address', models.CharField(max_length=127)),
                ('date', models.DateTimeField()),
                ('approve', models.BinaryField(default=False)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.pet')),
                ('unm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.user')),
            ],
        ),
    ]
