# Generated by Django 4.0.5 on 2022-07-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_adoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=127)),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
                ('enable', models.BinaryField(default=False)),
            ],
        ),
    ]
