# Generated by Django 4.0.5 on 2022-07-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='unm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.user'),
        ),
    ]
