# Generated by Django 4.0.5 on 2022-07-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_adoption_approve_alter_adoption_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='approve',
            field=models.BinaryField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='enable',
            field=models.BinaryField(default=False),
        ),
    ]
